# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 08:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0005_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundWebhookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('timestamp', models.DateTimeField()),
                ('message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('daily_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_requests', to='updates.Update')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
