# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0007_auto_20160509_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
