# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0008_team_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='subaccount_id',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
