# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0009_team_subaccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='silent_recipients',
            field=models.ManyToManyField(blank=True, help_text='These are the non-team members that need to receive team updates via email such as clients.                   They can access the platform using their email and password.', to='updates.SilentRecipient'),
        ),
    ]
