# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0010_team_silent_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='updates.Role'),
        ),
    ]
